
version: "3"
services:
  emily-text-recognition-api-17ma5n:
    image: emily-text-recognition-api-17ma5n
    container_name: emily-text-recognition-api-17ma5n
    networks:
      - emily-text-recognition-api-17ma5n-network
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - ${MOUNT1}:/workspace/text-recognition/
    runtime: ${RUNTIME}
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
    ipc: ${IPC}
networks:
  emily-text-recognition-api-17ma5n-network:
    name: emily-text-recognition-api-17ma5n-network
    driver: bridge
  
